server:
  port: 8014
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
# 设置全局编码格式
spring:
  application:
    name: LocalMcpServer
  ai:
    mcp:
      server:
        type: async
        name: customer-define-mcp-server
        version: 1.0.0
          # 关键：暴露 SSE 端点
        sse-path: /mcp          # 默认就是 /mcp，可省略
